import type { ControlActionDefinition } from './controls_registry.js';

export const PAINTER_CONTROLS_PROFILE: ControlActionDefinition[] = [
  { id: 'painter.tool_target_invert', label: 'Hold Invert Tool Target', category: 'Selection', system: 'painter', default_binding: { kind: 'keyboard', code: 'Backquote' } },
  { id: 'painter.view.swing_left', label: 'Swing View Left', category: 'Camera', system: 'painter', default_binding: { kind: 'keyboard', code: 'Numpad4' } },
  { id: 'painter.view.swing_right', label: 'Swing View Right', category: 'Camera', system: 'painter', default_binding: { kind: 'keyboard', code: 'Numpad6' } },
  { id: 'painter.view.swing_up', label: 'Swing View Up', category: 'Camera', system: 'painter', default_binding: { kind: 'keyboard', code: 'Numpad8' } },
  { id: 'painter.view.swing_down', label: 'Swing View Down', category: 'Camera', system: 'painter', default_binding: { kind: 'keyboard', code: 'Numpad2' } },
  { id: 'painter.view.roll_left', label: 'Roll View Left', category: 'Camera', system: 'painter', default_binding: { kind: 'keyboard', code: 'Numpad7' } },
  { id: 'painter.view.roll_right', label: 'Roll View Right', category: 'Camera', system: 'painter', default_binding: { kind: 'keyboard', code: 'Numpad9' } },
  { id: 'painter.view.depth_prev', label: 'Focus Depth Previous', category: 'Camera', system: 'painter', default_binding: { kind: 'keyboard', code: 'Numpad1' } },
  { id: 'painter.view.depth_next', label: 'Focus Depth Next', category: 'Camera', system: 'painter', default_binding: { kind: 'keyboard', code: 'Numpad3' } },
  { id: 'painter.breath.step_back', label: 'Step Breath Back', category: 'Timing', system: 'painter', default_binding: { kind: 'keyboard', code: 'Comma' } },
  { id: 'painter.breath.step_forward', label: 'Step Breath Forward', category: 'Timing', system: 'painter', default_binding: { kind: 'keyboard', code: 'Period' } },
  { id: 'painter.breath.play_pause', label: 'Toggle Playback', category: 'Timing', system: 'painter', default_binding: { kind: 'keyboard', code: 'Space' } },
  { id: 'painter.breath.jump_start', label: 'Jump To Start Breath', category: 'Timing', system: 'painter', default_binding: { kind: 'keyboard', code: 'BracketLeft' } },
  { id: 'painter.breath.jump_end', label: 'Jump To End Breath', category: 'Timing', system: 'painter', default_binding: { kind: 'keyboard', code: 'BracketRight' } },
  { id: 'painter.group.nudge_left', label: 'Nudge Group Left', category: 'Group', system: 'painter', default_binding: { kind: 'keyboard', code: 'ArrowLeft' } },
  { id: 'painter.group.nudge_right', label: 'Nudge Group Right', category: 'Group', system: 'painter', default_binding: { kind: 'keyboard', code: 'ArrowRight' } },
  { id: 'painter.group.nudge_up', label: 'Nudge Group Up', category: 'Group', system: 'painter', default_binding: { kind: 'keyboard', code: 'ArrowUp' } },
  { id: 'painter.group.nudge_down', label: 'Nudge Group Down', category: 'Group', system: 'painter', default_binding: { kind: 'keyboard', code: 'ArrowDown' } },
  { id: 'painter.tool_assign.pencil', label: 'Assign Pencil Tool', category: 'Tools', system: 'painter', default_binding: { kind: 'keyboard', code: 'KeyP' } },
  { id: 'painter.tool_assign.eraser', label: 'Assign Eraser Tool', category: 'Tools', system: 'painter', default_binding: { kind: 'keyboard', code: 'KeyE' } },
  { id: 'painter.tool_assign.bucket', label: 'Assign Bucket Tool', category: 'Tools', system: 'painter', default_binding: { kind: 'keyboard', code: 'KeyB' } },
  { id: 'painter.tool_assign.eyedropper', label: 'Assign Eyedropper Tool', category: 'Tools', system: 'painter', default_binding: { kind: 'keyboard', code: 'KeyI' } },
  { id: 'painter.tool_assign.line', label: 'Assign Line Tool', category: 'Tools', system: 'painter', default_binding: { kind: 'keyboard', code: 'KeyL' } },
  { id: 'painter.tool_assign.rect_stroke', label: 'Assign Rect Stroke Tool', category: 'Tools', system: 'painter', default_binding: { kind: 'keyboard', code: 'KeyR' } },
  { id: 'painter.tool_assign.rect_fill', label: 'Assign Rect Fill Tool', category: 'Tools', system: 'painter', default_binding: { kind: 'keyboard', code: 'KeyS' } },
  { id: 'painter.tool_assign.text', label: 'Assign Text Tool', category: 'Tools', system: 'painter', default_binding: { kind: 'keyboard', code: 'KeyT' } },
  { id: 'painter.tool_assign.selectangle', label: 'Assign Rect Selection Tool', category: 'Tools', system: 'painter', default_binding: { kind: 'keyboard', code: 'KeyM' } },
  { id: 'painter.tool_assign.lassoselect', label: 'Assign Lasso Selection Tool', category: 'Tools', system: 'painter', default_binding: { kind: 'keyboard', code: 'KeyN' } },
  { id: 'painter.tool_assign.copy', label: 'Assign Copy Tool', category: 'Tools', system: 'painter', default_binding: { kind: 'keyboard', code: 'KeyC' } },
  { id: 'painter.tool_assign.paste', label: 'Assign Paste Tool', category: 'Tools', system: 'painter', default_binding: { kind: 'keyboard', code: 'KeyV' } },
  { id: 'painter.tool_assign.move', label: 'Assign Move Tool', category: 'Tools', system: 'painter', default_binding: { kind: 'keyboard', code: 'KeyG' } },
];
