import type { ControlActionDefinition } from './controls_registry.js';

export const PAINTER_CONTROLS_PROFILE: ControlActionDefinition[] = [
  { id: 'painter.tool_target_invert', label: 'Hold Invert Tool Target', category: 'Selection', system: 'painter', default_binding: { kind: 'keyboard', code: 'Backquote' } },
  { id: 'painter.view.swing_left', label: 'Swing View Left', category: 'Camera', system: 'painter', default_binding: { kind: 'keyboard', code: 'Numpad4' } },
  { id: 'painter.view.swing_right', label: 'Swing View Right', category: 'Camera', system: 'painter', default_binding: { kind: 'keyboard', code: 'Numpad6' } },
  { id: 'painter.view.swing_up', label: 'Swing View Up', category: 'Camera', system: 'painter', default_binding: { kind: 'keyboard', code: 'Numpad8' } },
  { id: 'painter.view.swing_down', label: 'Swing View Down', category: 'Camera', system: 'painter', default_binding: { kind: 'keyboard', code: 'Numpad2' } },
  { id: 'painter.view.roll_left', label: 'Roll View Left', category: 'Camera', system: 'painter', default_binding: { kind: 'keyboard', code: 'Numpad7' } },
  { id: 'painter.view.roll_right', label: 'Roll View Right', category: 'Camera', system: 'painter', default_binding: { kind: 'keyboard', code: 'Numpad9' } },
  { id: 'painter.view.depth_prev', label: 'Focus Depth Previous', category: 'Camera', system: 'painter', default_binding: { kind: 'keyboard', code: 'Numpad1' } },
  { id: 'painter.view.depth_next', label: 'Focus Depth Next', category: 'Camera', system: 'painter', default_binding: { kind: 'keyboard', code: 'Numpad3' } },
  { id: 'painter.breath.step_back', label: 'Step Breath Back', category: 'Timing', system: 'painter', default_binding: { kind: 'keyboard', code: 'ArrowLeft' } },
  { id: 'painter.breath.step_forward', label: 'Step Breath Forward', category: 'Timing', system: 'painter', default_binding: { kind: 'keyboard', code: 'ArrowRight' } },
  { id: 'painter.breath.jump_active_group_start', label: 'Jump To Active Group Start', category: 'Timing', system: 'painter', default_binding: { kind: 'keyboard', code: 'ArrowUp' } },
  { id: 'painter.breath.jump_active_group_end', label: 'Jump To Active Group End', category: 'Timing', system: 'painter', default_binding: { kind: 'keyboard', code: 'ArrowDown' } },
  { id: 'painter.breath.play_pause', label: 'Toggle Transport (Last Direction)', category: 'Timing', system: 'painter', default_binding: { kind: 'keyboard', code: 'Space' } },
  { id: 'painter.breath.jump_start', label: 'Jump To Start Breath', category: 'Timing', system: 'painter', default_binding: { kind: 'keyboard', code: 'BracketLeft' } },
  { id: 'painter.breath.jump_end', label: 'Jump To End Breath', category: 'Timing', system: 'painter', default_binding: { kind: 'keyboard', code: 'BracketRight' } },
  { id: 'painter.scroll.primary_prev', label: 'Scroll Depth Previous', category: 'Scroll', system: 'painter', default_binding: { kind: 'wheel', direction: 'up' } },
  { id: 'painter.scroll.primary_next', label: 'Scroll Depth Next', category: 'Scroll', system: 'painter', default_binding: { kind: 'wheel', direction: 'down' } },
  { id: 'painter.scroll.secondary_prev', label: 'Scroll Time Previous', category: 'Scroll', system: 'painter', default_binding: { kind: 'wheel', direction: 'up', alt: true } },
  { id: 'painter.scroll.secondary_next', label: 'Scroll Time Next', category: 'Scroll', system: 'painter', default_binding: { kind: 'wheel', direction: 'down', alt: true } },
  { id: 'painter.scroll.pan_vertical_prev', label: 'Scroll Pan Vertical Previous', category: 'Scroll', system: 'painter', default_binding: { kind: 'wheel', direction: 'up', held_keys: ['Space'] } },
  { id: 'painter.scroll.pan_vertical_next', label: 'Scroll Pan Vertical Next', category: 'Scroll', system: 'painter', default_binding: { kind: 'wheel', direction: 'down', held_keys: ['Space'] } },
  { id: 'painter.scroll.pan_horizontal_prev', label: 'Scroll Pan Horizontal Previous', category: 'Scroll', system: 'painter', default_binding: { kind: 'wheel', direction: 'up', alt: true, held_keys: ['Space'] } },
  { id: 'painter.scroll.pan_horizontal_next', label: 'Scroll Pan Horizontal Next', category: 'Scroll', system: 'painter', default_binding: { kind: 'wheel', direction: 'down', alt: true, held_keys: ['Space'] } },
  { id: 'painter.position.nudge_left', label: 'Position Nudge Left', category: 'Position', system: 'painter', default_binding: { kind: 'keyboard', code: 'KeyA' } },
  { id: 'painter.position.nudge_right', label: 'Position Nudge Right', category: 'Position', system: 'painter', default_binding: { kind: 'keyboard', code: 'KeyD' } },
  { id: 'painter.position.nudge_up', label: 'Position Nudge Up', category: 'Position', system: 'painter', default_binding: { kind: 'keyboard', code: 'KeyW' } },
  { id: 'painter.position.nudge_down', label: 'Position Nudge Down', category: 'Position', system: 'painter', default_binding: { kind: 'keyboard', code: 'KeyS' } },
  { id: 'painter.position.nudge_backward', label: 'Position Nudge Backward', category: 'Position', system: 'painter', default_binding: { kind: 'keyboard', code: 'KeyZ' } },
  { id: 'painter.position.nudge_forward', label: 'Position Nudge Forward', category: 'Position', system: 'painter', default_binding: { kind: 'keyboard', code: 'KeyX' } },
  { id: 'painter.position.rotate_left', label: 'Position Rotate Left', category: 'Position', system: 'painter', default_binding: { kind: 'keyboard', code: 'KeyQ' } },
  { id: 'painter.position.rotate_right', label: 'Position Rotate Right', category: 'Position', system: 'painter', default_binding: { kind: 'keyboard', code: 'KeyE' } },
  { id: 'painter.edit.undo', label: 'Undo', category: 'Edit', system: 'painter', default_binding: { kind: 'keyboard', code: 'KeyZ', ctrl: true } },
  { id: 'painter.edit.redo', label: 'Redo', category: 'Edit', system: 'painter', default_binding: { kind: 'keyboard', code: 'KeyY', ctrl: true } },
  { id: 'painter.edit.copy', label: 'Copy Selection', category: 'Edit', system: 'painter', default_binding: { kind: 'keyboard', code: 'KeyC', ctrl: true } },
  { id: 'painter.tool_assign.pencil', label: 'Assign Pencil Tool', category: 'Tools', system: 'painter', default_binding: { kind: 'keyboard', code: 'Digit1' } },
  { id: 'painter.tool_assign.eraser', label: 'Assign Eraser Tool', category: 'Tools', system: 'painter', default_binding: { kind: 'keyboard', code: 'Digit2' } },
  { id: 'painter.tool_assign.bucket', label: 'Assign Bucket Tool', category: 'Tools', system: 'painter', default_binding: { kind: 'keyboard', code: 'Digit3' } },
  { id: 'painter.tool_assign.eyedropper', label: 'Assign Eyedropper Tool', category: 'Tools', system: 'painter', default_binding: { kind: 'keyboard', code: 'Digit4' } },
  { id: 'painter.tool_assign.line', label: 'Assign Line Tool', category: 'Tools', system: 'painter', default_binding: { kind: 'keyboard', code: 'Digit5' } },
  { id: 'painter.tool_assign.rect_stroke', label: 'Assign Rect Stroke Tool', category: 'Tools', system: 'painter', default_binding: { kind: 'keyboard', code: 'Digit6' } },
  { id: 'painter.tool_assign.rect_fill', label: 'Assign Rect Fill Tool', category: 'Tools', system: 'painter', default_binding: { kind: 'keyboard', code: 'Digit7' } },
  { id: 'painter.tool_assign.shape', label: 'Assign Shape Tool', category: 'Tools', system: 'painter', default_binding: null },
  { id: 'painter.tool_assign.text', label: 'Assign Text Tool', category: 'Tools', system: 'painter', default_binding: { kind: 'keyboard', code: 'Digit8' } },
  { id: 'painter.tool_assign.lassoselect', label: 'Assign Lasso Selection Tool', category: 'Tools', system: 'painter', default_binding: null },
  { id: 'painter.tool_assign.copy', label: 'Assign Copy Tool', category: 'Tools', system: 'painter', default_binding: null },
  { id: 'painter.tool_assign.paste', label: 'Assign Paste Tool', category: 'Tools', system: 'painter', default_binding: null },
  { id: 'painter.tool_assign.move', label: 'Assign Move Tool', category: 'Tools', system: 'painter', default_binding: { kind: 'keyboard', code: 'Digit9' } },
];
